export default [
"Modern Philosophy: Theories of Time and Temporality",
"Advanced Organic Chemistry: Synthesis and Applications",
"Disaster Preparedness and Emergency Management",
"Introduction to Quantum Mechanics and Applications",
"Folklore Studies: Myths, Legends, and Cultural Impact",
"Cognitive Psychology: Understanding Mental Processes",
"Internet Culture and Social Media Trends",
"Biomedical Engineering: Innovations in Prosthetics",
"Mindfulness and Stress Management Techniques",
"Robotics: Theory and Practice",
"Sports Analytics: Data-Driven Decision Making",
"European History: Medieval to Modern Perspectives",
"Psychology of Belief Systems and Group Behavior",
"Media Studies: Fan Cultures and Participatory Media",
"Meteorology: Extreme Weather Phenomena and Analysis",
"Urban Legends and Contemporary Folklore",
"Mathematical Modeling in Biology and Medicine",
"Cybersecurity Fundamentals and Threat Mitigation",
"Quantum Mechanics: Principles and Applications",
"Multicultural Cuisine: Culinary Traditions from Around the World",
"Time Management and Productivity Strategies",
"Advanced Computer Programming: Algorithms and Data Structures",
"Environmental Science: Sustainability and Conservation",
"Ancient Mythology and Its Relevance Today",
"Space Exploration: Past, Present, and Future",
"Telecommunications Engineering: Principles and Applications",
"Supernatural Phenomena",
"History of Economic Thought and Policy Analysis",
"Neuroscience and Behavior: Understanding the Brain",
"Literary Studies: Classic and Contemporary Perspectives",
"Environmental Sustainability and Policy",
"Artificial Intelligence: Principles and Applications",
"Global Health Issues and Solutions",
"Cultural Anthropology: Exploring Human Diversity",
"Business Ethics and Corporate Responsibility",
"Digital Marketing Strategies and Analytics",
"Public Speaking and Persuasion Techniques",
"Entrepreneurship: From Idea to Business Plan",
"International Relations: Theory and Practice",
"Sociology of Gender and Sexuality",
"Modern Architecture and Urban Planning",
"Data Visualization and Infographics",
"Environmental Ethics and Conservation",
"Managerial Accounting: Decision-Making Tools",
"Developmental Psychology: Lifespan Perspectives",
"Music Appreciation: Styles and Influences",
"International Business Law and Ethics",
"Creative Writing: Fiction and Non-Fiction",
"Investment Analysis and Portfolio Management",
"Human Rights and Social Justice",
"Consumer Behavior and Market Research",
"Nutrition and Health: Principles and Applications",
"Organizational Behavior and Leadership",
"Introduction to Comparative Politics",
"Graphic Design Fundamentals",
"Applied Statistics for Social Sciences",
"Financial Management: Concepts and Cases",
"Social Media Marketing Strategies",
"Cognitive Neuroscience: Brain and Behavior",
"Strategic Management: Theory and Practice",
"American Literature: From Colonial to Contemporary",
"Globalization and Its Discontents",
"Computer Networks and Security",
"Healthcare Policy and Management",
"Introduction to Archaeology",
"Film Studies: History and Theory",
"Operations Management: Concepts and Applications",
"Human Resource Management: Theory and Practice",
"Principles of Microeconomics",
"Urban Sociology: Cities and Communities",
"Corporate Finance: Theory and Practice",
"Human Development and Family Studies",
"Digital Photography: Techniques and Composition",
"Principles of Marketing: Concepts and Applications",
"Media Ethics and Law",
"International Trade and Finance",
"Organizational Behavior and Leadership",
"Introduction to Microeconomics",
"Public Policy Analysis and Evaluation",
"Introduction to Environmental Studies",
"Principles of Management",
"Research Methods in Psychology",
"Digital Advertising and Branding",
"Fundamentals of Human Nutrition",
"Introduction to Anthropology",
"Entrepreneurial Finance and Venture Capital",
"Global Environmental Issues and Solutions",
"Introduction to International Development",
"Principles of Public Relations",
"Social Problems and Solutions",
"Corporate Governance and Ethics",
"Introduction to Computer Science",
"Fundamentals of Finance",
"Political Economy of Development",
"Consumer Psychology and Behavior",
"Business Law and Ethics",
"Introduction to Public Health",
"Managerial Decision Making",
"Fundamentals of Marketing",
"Introduction to Linguistics",
"Introduction to Philosophy",
"Business Strategy and Competition",
"Introduction to Criminal Justice",
"Human Resource Development",
"Introduction to Cultural Anthropology",
"Principles of Macroeconomics",
"Introduction to Political Philosophy",
"Social Media Management",
"Introduction to Film Studies",
"Fundamentals of Organizational Communication",
"Introduction to Statistics",
"Introduction to Art History",
"Globalization and Development",
"Psychological Testing and Assessment",
"Introduction to Global Health",
"Introduction to Geography",
"Leadership and Team Dynamics",
"Introduction to American Government",
"Introduction to Literature",
"Entrepreneurship and Innovation",
"Introduction to Sociology of Religion",
"Fundamentals of Public Speaking",
"Introduction to Educational Psychology",
"Introduction to Music Theory",
"Health Communication and Advocacy",
"Introduction to Environmental Economics",
"Globalization and Cultural Diversity",
"Introduction to Gender Studies",
"Human Resource Management Principles",
"Introduction to Astronomy",
"Social Justice and Diversity",
"Introduction to Theater Arts",
"Business Analytics and Decision Making",
"Introduction to Developmental Psychology",
"Fundamentals of Web Design",
"Introduction to Archaeology",
"Introduction to Criminal Law",
"Digital Journalism and New Media",
"Introduction to Cultural Studies",
"Introduction to Linguistic Anthropology",
"Managerial Accounting and Control",
"Introduction to Social Work",
"Introduction to Comparative Literature",
"Introduction to Political Economy",
"Digital Storytelling and Multimedia Production",
"Introduction to Urban Studies",
];
